alias bash-aliases="vim ~/.bash_aliases"
alias bluetoothoff="rfkill block bluetooth"
alias bluetoothon="rfkill unblock bluetooth"
alias cls="clear"
alias conda="~/anaconda3/condabin/conda"
alias cpuinfo='cat /proc/cpuinfo'
alias eclipse="~/eclipse/java-2018-12/eclipse/eclipse"
alias gotorxjava="cd ~/Documents/progs/RxJava"
alias jupyter-notebook="~/anaconda3/bin/jupyter-notebook"
alias lash="ls -lash"
alias loadXdefaults="xrdb -load ~/.Xdefaults"
alias ls="ls -1 --color=auto"
alias lsa="ls -a"
alias mysqlroot="sudo mysql -u root"
alias networkinfo="cd /etc/NetworkManager/system-connections/; ll; cd -"
alias numfiles="ls -l | wc -l"
alias os-release="cat /usr/lib/os-release"
alias perl-lib="/usr/lib/x86_64-linux-gnu/urxvt/perl"
alias perlscripts="cd /usr/lib/x86_64-linux-gnu/urxvt/perl"
alias pingtest="ping -c 4 www.google.com"
alias playmagic="lutris lutris:rungameid/1"
alias pythonprogs="cd ~/python_progs"
alias ranger='ranger --choosedir=$HOME/.rangerdir; LASTDIR=`cat $HOME/.rangerdir`; cd "$LASTDIR"'
alias saptupdate="sudo apt update"
alias saptupgrade="sudo apt upgrade"
alias stopapache2="sudo systemctl stop apache2"
alias sublime='/snap/current/sublime_text'
alias systemsuspend="systemctl suspend"
alias ts3client="~/packages/TeamSpeak3-Client-linux_amd64/ts3client_runscript.sh"
alias vim="vi"
# alias clspackagecache="sudo rm /var/lib/apt/lists/*"
# Git aliases

# alias lg1="git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)' --all"
# alias lg2="git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold green)(%ar)%C(reset)%C(bold yellow)%d%C(reset)%n''          %C(white)%s%C(reset) %C(dim white)- %an%C(reset)' --all"
# alias lg=!"git lg1"
